import Head from "next/head";
import React from "react";
import dynamic from "next/dynamic";

import styles from "../styles/Home.module.css";
import officesByDistrictsJson from "../public/offices_by_districts.json";
import peopleByDistrictsJson from "../public/people_by_districts.json";

const Map = dynamic(() => import("../components/Map"), { ssr: false });

export default function Home({ peopleByDistricts, officesByDistricts }) {
  const peopleCount = React.useMemo(() => {
    return Object.values(peopleByDistricts).reduce(
      (carry, value) => carry + value,
      0
    );
  }, [peopleByDistricts]);

  const officesCount = React.useMemo(() => {
    return Object.values(officesByDistricts).reduce(
      (carry, value) => carry + value,
      0
    );
  }, [officesByDistricts]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>
        Lékaři pomáhají Česku - demo interaktivní mapy nad Google Spreadsheetem
      </h1>

      <h2>Registrace</h2>

      <p>
        <a
          href="https://docs.google.com/forms/d/e/1FAIpQLSfNKPYGtcqbIG3aWQLOGG6GaomUV2dxAUb1Tnp-GXuVHWZKLA/viewform?usp=sf_link"
          target="_blank"
          rel="noreferrer"
        >
          Budu očkovat ve své ordinaci →
        </a>
      </p>

      <p>
        <a
          href="https://docs.google.com/forms/d/e/1FAIpQLSfD_D9MDgjc6hVlAMTmQmiIrg_MDQwi8sGIpffeB7nsg3mUmQ/viewform?usp=sf_link"
          target="_blank"
          rel="noreferrer"
        >
          Chci pomoci v očkovacím místě →
        </a>
      </p>

      <h2>
        Aktuálně {peopleCount} osob a {officesCount} ordinací
      </h2>

      <Map
        peopleByDistricts={peopleByDistricts}
        officesByDistricts={officesByDistricts}
      />
    </div>
  );
}

export async function getStaticProps(context) {
  return {
    props: {
      officesByDistricts: officesByDistrictsJson,
      peopleByDistricts: peopleByDistrictsJson,
    },
  };
}
